/* eslint-disable react/no-children-prop */
import type { Metadata } from "next";
// import Head from "next/head";

import "bootstrap/dist/css/bootstrap.min.css";
import "./../styles/global.scss";
import Layout from "../components/layout";
export const metadata: Metadata = {
  title: "Create Blog Post",
  description: "Generated by create next app",
  icons: {
    icon: "/thumbnail-default.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
